image: rtcamp/gitlab-aws-codecommit-mirror
stages:
  - deploy

deploy to production:
  tags:
    - codecommit
  stage: deploy
  script:
    - bash setup_ssh
    - git clone --mirror $SOURCE_REPO rtSync
    - cd rtSync
    - git branch -a
    - git push --mirror $SCHEME://$REPO_URL